# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Fatigue_Detection\src\ui\main_interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_interface(object):
    def setupUi(self, main_interface):
        main_interface.setObjectName("main_interface")
        main_interface.resize(1135, 887)
        self.centralwidget = QtWidgets.QWidget(main_interface)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_display = QtWidgets.QLabel(self.centralwidget)
        self.lb_display.setFrameShape(QtWidgets.QFrame.Panel)
        self.lb_display.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lb_display.setObjectName("lb_display")
        self.horizontalLayout.addWidget(self.lb_display)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.le_cam_index = QtWidgets.QLineEdit(self.groupBox_2)
        self.le_cam_index.setObjectName("le_cam_index")
        self.horizontalLayout_3.addWidget(self.le_cam_index)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 5)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.btn_start.setCheckable(True)
        self.btn_start.setFlat(False)
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout_7.addWidget(self.btn_start)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.setStretch(0, 7)
        self.verticalLayout_3.setStretch(1, 3)
        main_interface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_interface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1135, 23))
        self.menubar.setObjectName("menubar")
        main_interface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_interface)
        self.statusbar.setObjectName("statusbar")
        main_interface.setStatusBar(self.statusbar)

        self.retranslateUi(main_interface)
        QtCore.QMetaObject.connectSlotsByName(main_interface)

    def retranslateUi(self, main_interface):
        _translate = QtCore.QCoreApplication.translate
        main_interface.setWindowTitle(_translate("main_interface", "MainWindow"))
        self.lb_display.setText(_translate("main_interface", "TextLabel"))
        self.label_2.setText(_translate("main_interface", "疲劳状态："))
        self.label.setText(_translate("main_interface", "摄像头索引："))
        self.btn_start.setText(_translate("main_interface", "启动"))

